#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing pi cpu temperature display...\n"
sudo cp pi-cpu-temperature-display.py /usr/local/bin/
sudo chmod +x /usr/local/bin/pi-cpu-temperature-display.py

echo "=> Starting pi cpu temperature display...\n"
sudo cp pi-cpu-temperature-display.sh /etc/init.d/
sudo chmod +x /etc/init.d/pi-cpu-temperature-display.sh

sudo update-rc.d pi-cpu-temperature-display.sh defaults
sudo /etc/init.d/pi-cpu-temperature-display.sh start

echo "pi-cpu-temperature-display installed.\n"