#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping pi cpu temperature display...\n"
sudo update-rc.d pi-cpu-temperature-display.sh remove
sudo /etc/init.d/pi-cpu-temperature-display.sh stop

echo "=> Removing pi cpu temperature display...\n"
sudo rm -rf /usr/local/bin/pi-cpu-temperature-display.py 
sudo rm -rf /etc/init.d/pi-cpu-temperature-display.sh 

echo "Pi CPU Temperature display uninstalled.\n"
